#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deap
Version  : 1.0.1
Release  : 5
URL      : https://github.com/DEAP/deap/archive/1.0.1.tar.gz
Source0  : https://github.com/DEAP/deap/archive/1.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: deap-legacypython
Requires: deap-python3
Requires: deap-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
DEAP stands for Distributed Evolutionary Algorithm in Python, it is dedicated to people who
wish to learn how to use evolutionary algorithms and to those who wish to
rediscover evolutionary algorithms. DEAP is the proof that evolutionary
algorithms do **not** need to be neither complex or complicated.

%package legacypython
Summary: legacypython components for the deap package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deap package.


%package python
Summary: python components for the deap package.
Group: Default
Requires: deap-legacypython
Requires: deap-python3

%description python
python components for the deap package.


%package python3
Summary: python3 components for the deap package.
Group: Default
Requires: python3-core

%description python3
python3 components for the deap package.


%prep
%setup -q -n deap-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507153029
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1507153029
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
